### Obtener todos los usuarios
GET http://localhost:8080/api/users


### Obtener un usuario por su id
GET http://localhost:8080/api/users/1


### Crear un usuario
POST http://localhost:8080/api/users
Content-Type: application/json


{
  "name": "Carlos",
  "phone": "3225469",
  "city": "Armenia",
  "address": "Calle 123",
  "email": "carlos@email.com",
  "password": "1234567"
}


### Actualizar un usuario
PUT http://localhost:8080/api/users
Content-Type: application/json


{
  "idUser": 1,
  "name": "Carlos",
  "phone": "3225479",
  "city": "Armenia",
  "address": "Nueva dirección"
}


### Eliminar un usuario
DELETE http://localhost:8080/api/users/1

### Obtener todos los usuarios que tengan un nombre dado
GET http://localhost:8080/api/users?name=Carlos


### Obtener todos los usuarios cuya ciudad de residencia sea Armenia
GET http://localhost:8080/api/users?city=Armenia


### Obtener todos los usuarios cuya ciudad de residencia sea Armenia y su nombre sea Carlos
GET http://localhost:8080/api/users?name=Carlos&city=armenia&page=0
